"""empty message

Revision ID: 24812087d9a3
Revises: ef28c0fa8d89
Create Date: 2025-01-31 13:53:24.431847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24812087d9a3'
down_revision = 'ef28c0fa8d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_spots', schema=None) as batch_op:
        batch_op.drop_column('season_points')

    # ### end Alembic commands ###
