"""empty message

Revision ID: 35333ffe0ba2
Revises: b70150ba3247
Create Date: 2025-02-06 15:42:09.059341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35333ffe0ba2'
down_revision = 'b70150ba3247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
