"""empty message

Revision ID: 76002d38f129
Revises: f8b39f1bf8cf
Create Date: 2025-01-31 13:06:56.174578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76002d38f129'
down_revision = 'f8b39f1bf8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_points', sa.JSON(), nullable=False))
        batch_op.drop_column('week_25_points')
        batch_op.drop_column('week_38_points')
        batch_op.drop_column('week_33_points')
        batch_op.drop_column('week_40_points')
        batch_op.drop_column('week_24_points')
        batch_op.drop_column('week_7_points')
        batch_op.drop_column('week_34_points')
        batch_op.drop_column('week_43_points')
        batch_op.drop_column('week_26_points')
        batch_op.drop_column('week_31_points')
        batch_op.drop_column('week_42_points')
        batch_op.drop_column('week_1_points')
        batch_op.drop_column('week_29_points')
        batch_op.drop_column('week_20_points')
        batch_op.drop_column('week_19_points')
        batch_op.drop_column('week_35_points')
        batch_op.drop_column('week_17_points')
        batch_op.drop_column('week_39_points')
        batch_op.drop_column('week_5_points')
        batch_op.drop_column('week_14_points')
        batch_op.drop_column('week_21_points')
        batch_op.drop_column('week_13_points')
        batch_op.drop_column('week_4_points')
        batch_op.drop_column('week_36_points')
        batch_op.drop_column('week_22_points')
        batch_op.drop_column('week_23_points')
        batch_op.drop_column('week_9_points')
        batch_op.drop_column('week_15_points')
        batch_op.drop_column('week_11_points')
        batch_op.drop_column('week_16_points')
        batch_op.drop_column('week_41_points')
        batch_op.drop_column('week_6_points')
        batch_op.drop_column('week_37_points')
        batch_op.drop_column('week_2_points')
        batch_op.drop_column('week_10_points')
        batch_op.drop_column('week_27_points')
        batch_op.drop_column('week_44_points')
        batch_op.drop_column('week_12_points')
        batch_op.drop_column('week_28_points')
        batch_op.drop_column('week_30_points')
        batch_op.drop_column('week_32_points')
        batch_op.drop_column('week_8_points')
        batch_op.drop_column('week_3_points')
        batch_op.drop_column('week_18_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_18_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_3_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_8_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_32_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_30_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_28_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_12_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_44_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_27_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_10_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_2_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_37_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_6_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_41_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_16_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_11_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_15_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_9_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_23_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_22_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_36_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_4_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_13_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_21_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_14_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_5_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_39_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_17_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_35_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_19_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_20_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_29_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_1_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_42_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_31_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_26_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_43_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_34_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_7_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_24_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_40_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_33_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_38_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_25_points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('week_points')

    # ### end Alembic commands ###
