"""empty message

Revision ID: ef28c0fa8d89
Revises: 76002d38f129
Create Date: 2025-01-31 13:50:25.000929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ef28c0fa8d89'
down_revision = '76002d38f129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_points', sa.Integer(), nullable=True))
        batch_op.drop_column('week_points')

    with op.batch_alter_table('roster_spots', schema=None) as batch_op:
        batch_op.drop_column('week')
        batch_op.drop_column('week_points')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))
        batch_op.drop_column('week_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_score', sa.INTEGER(), nullable=True))
        batch_op.drop_column('locked')

    with op.batch_alter_table('roster_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_points', sqlite.JSON(), nullable=False))
        batch_op.drop_column('season_points')

    # ### end Alembic commands ###
